### ISSUE TITLE
java.lang.ClassCastException: org.eclipse.paho.android.service.MqttTokenAndroid cannot be cast to org.eclipse.paho.client.mqttv3.IMqttDeliveryToken

### ISSUE THREAD

**Issue by dmsherazi** [dmsherazi/BugsAndCrashesForChitChat#8]
```bash
java.lang.ClassCastException: org.eclipse.paho.android.service.MqttTokenAndroid cannot be cast to org.eclipse.paho.client.mqttv3.IMqttDeliveryToken
	at org.eclipse.paho.android.service.MqttAndroidClient.messageDeliveredAction(MqttAndroidClient.java:1424)
	at org.eclipse.paho.android.service.MqttAndroidClient.onReceive(MqttAndroidClient.java:1280)
	at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
	at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
	at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:5389)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

```

**Comment by dmsherazi** [comment]
should be fixed by migrating to paho snapshot version
